# Generated by Django 3.2.7 on 2022-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='93619', max_length=100, verbose_name='Postal Code'),
        ),
    ]
